name: Upload To Azure Blob Storage
on:
  push:
    branches:
      - main
jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Build with Maven
        run: mvn package

      - name: Upload model to Azure Blob Storage
        env:
          AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
        run: java -cp target/playground-0.0.1-SNAPSHOT.jar ch.zhaw.deeplearningjava.playground.UploadToAzureBlobStorage

