name: Upload To Azure Blob Storage
on:
  push:
    branches:
      - main
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bacongobbler/azure-blob-storage-upload@main
        with:
          source_dir: models
          container_name: ulricdo1emotiondetection
          connection_string: '${{secrets.AZURE_STORAGE_CONNECTION_STRING}}'
          extra_args: '--include "*.params" --include "*.txt"'
          overwrite: 'true'